basePath: /api/v1
host: localhost:8080
info:
  contact:
    name: Ademar Junior
  description: Api responsável por gerenciar os recursos de Feature Toggle do sicredi
    mobi.
  title: Feature Toggle API
  version: "1.0"
paths: {}
swagger: "2.0"
